### ISSUE TITLE
Is flag --config being used?

### ISSUE THREAD

**Issue by mimimalizam** [semaphoreci/artifact#19]
@vendelin8 :wave: I'm currently writing documentation page for `artifact` CLI and I'm not sure if this flag is intended or deprecated.

When running `artifact pull job` (without arguments) I noticed the following lines in the output log
```

Global Flags:
      --config string   config file (default is $HOME/.artifact.yaml)
```

**Comment by vendelin8** [comment]
Currently there are 3 variables that may be in the config file. And the config file may have a different location than the default. So technically it works, not really useful, if you ask me :)
https://github.com/semaphoreci/artifact#configs
