### ISSUE TITLE
`sem artifact` would be the only cli-way to download the artifacts, when will it ship?

### ISSUE THREAD

**Issue by fwolfst** [semaphoreci/artifact#55]
Afaict, `sem artifact` would be the only "cli-way" to download artifacts. We'd really like that feature.

Its marked as a TODO, is there an estimation when it would ship?
🙏

**Comment by lucianoliberti** [comment]
@fwolfst does [this](https://docs.semaphoreci.com/reference/artifact-cli-reference/#downloading-artifacts) help?

**Comment by fwolfst** [comment]
@lucianoliberti `artifact` is only available on the semaphore machines afaiu. I want something to sometimes download a artifact to my local dev machine, without needing to employ the browser.

**Comment by lucianoliberti** [comment]
@fwolfst we don't plan to develop the `sem artifact` feature in the near future. We've removed it from the To Do. However, you can use the artifact CLI to download artifacts by exposing the proper environment variables (`SEMAPHORE_ORGANIZATION_URL` , `SEMAPHORE_ARTIFACT_TOKEN` , `SEMAPHORE_PROJECT_ID` , …) which are automatically exposed in a job in your local machine.

**Comment by fwolfst** [comment]
> @fwolfst we don't plan to develop the `sem artifact` feature in the near future. We've removed it from the To Do. However, you can use the artifact CLI to download artifacts by exposing the proper environment variables (`SEMAPHORE_ORGANIZATION_URL` , `SEMAPHORE_ARTIFACT_TOKEN` , `SEMAPHORE_PROJECT_ID` , …) which are automatically exposed in a job in your local machine.

Yes, that does the trick. Thanks.
