### ISSUE TITLE
Typo error in `path_resolver` package

### ISSUE THREAD

**Issue by vishal24367** [semaphoreci/artifact#59]
https://github.com/semaphoreci/artifact/blob/2f90de9c83cdb66403f77a4342288d6ef0b09e8f/pkg/files/path_resolver.go#L52

Current:
"project ID is not set. Please use the SEMAPHORE_JOB_ID environment variable or the --job-id parameter to configure it"

Excepted:
"job ID is not set. Please use the SEMAPHORE_JOB_ID environment variable or the --job-id parameter to configure it"

**Comment by lucianoliberti** [comment]
Thanks for reporting this, we'll assess it.
