### ISSUE TITLE
Flag: --expire-in 10d or -e 10d

### ISSUE THREAD

**Issue by darkofabijan** [semaphoreci/artifact#8]

**Comment by vendelin8** [comment]
A duration when the given path is deleted. The value is an integer plus a duration. Possible options:
* Nw for N weeks
* Nm for N months; where a month means 30 days
* Ny for N years
* `Never` or empty string means no expire, which is the default.

**Comment by darkofabijan** [comment]
Nd for n days should be also possible :)

**Comment by vendelin8** [comment]
Done.
